name: netsci-course
channels:
  - defaults
dependencies:
 - python
 - ipykernel
 - ipywidgets=7
 - tqdm
 - openpyxl
 - pandas=2.1.1
 - matplotlib
 - conda-forge::seaborn=0.13.1
 - networkx=3.3
 - powerlaw=1.4.6
